// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxvwzbmtcniontagzmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dnd6Ym10Y25pb250YWd6bWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NDQyMjgsImV4cCI6MjA3NDAyMDIyOH0.tGIbPuF995MQLbSYczklwPa82W9Z8L1V12a8dsu4Hyw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});